# These are supported funding model platforms

github: ubden
patreon: ubden
open_collective: ubden
ko_fi: ubden
liberapay: ubden
issuehunt: ubden
lfx_crowdfunding: ubden
buy_me_a_coffee: ubden
thanks_dev: ubden
